<!DOCTYPE html>
<html>
    <head>
        <title>GigaNinja</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta charset="UTF-8"/>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
        <link rel="stylesheet" href="<?= Assets\Asset::inc('assets/css/style.css') ?>"/>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>

    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a class="navbar-brand" href="#">GigaNinja</a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span class="navbar-toggler-icon"></span>
                        </button>

                        <div class="collapse navbar-collapse" id="navbarSupportedContent">
                            <ul class="navbar-nav mr-auto">
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= redirect('') ?>">Pagina Inicial</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= redirect('fornecedor') ?>">Fornecedor</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= redirect('produtos') ?>">Produtos</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="<?= redirect('registrarPedido') ?>">Registrar Pedido</a>
                                </li>
                            </ul>
                            <form class="form-inline my-2 my-lg-0">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                            </form>
                        </div>
                    </nav>
                </div>
            </div>
        </div>