<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                <div class="form-row">
                    <div class="form-group col-sm-12">
                        <label for="inputEmail4" class="col-form-label">Email</label>
                        <input type="text" name="email" class="form-control" value="<?=$data['email']?>">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAddress" class="col-form-label">Referencia</label>
                    <textarea rows="10" class="form-control" name="referencia">
                        <?=$data['referencia']?>
                    </textarea>
                </div>
                <button type="submit" class="btn btn-primary">Editar</button>
            </form>
        </div>
    </div>
</div>