<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                <div class="form-row">
                    <div class="form-group col-sm-12">
                        <label for="inputEmail4" class="col-form-label">DDD</label>
                        <input type="text" name="ddd" class="form-control" value="<?= $data['ddd'] ?>">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-sm-12">
                        <label for="inputEmail4" class="col-form-label">Numero</label>
                        <input type="text" name="numero" value="<?= $data['numero'] ?>" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAddress" class="col-form-label">Referencia</label>
                    <textarea rows="10" class="form-control" name="referencia">
                        <?= $data['referencia'] ?>
                    </textarea>
                </div>
                <button type="submit" class="btn btn-primary">Editar</button>
            </form>
        </div>
    </div>
</div>
