<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="jumbotron">
                <h1 class="display-3">Bem Vindo!</h1>
                <p class="lead">Projeto GigaNinja</p>
                <hr class="my-4">
                <p>Veja esse projeto no github</p>
                <p class="lead">
                    <a class="btn btn-primary btn-lg" href="#" role="button">GITHUB</a>
                </p>
            </div>
        </div>
    </div>
</div>