<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                <div class="form-row">
                    <div class="form-group col-sm-12">
                        <label for="inputEmail4" class="col-form-label">Nome</label>
                        <input type="text" name="nome" class="form-control" placeholder="Nome do produto">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAddress" class="col-form-label">Descrição</label>
                    <textarea rows="10" class="form-control" name="descricao">
                        
                    </textarea>
                </div>
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </form>
        </div>
    </div>
</div>