<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post">
                <div class="form-row">
                    <div class="form-group col-sm-12">
                        <label for="inputEmail4" class="col-form-label">Ddd</label>
                        <input type="text" name="ddd" class="form-control">
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-sm-12">
                        <label for="inputEmail4" class="col-form-label">Numero</label>
                        <input type="text" name="numero" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="inputAddress" class="col-form-label">Referencia</label>
                    <textarea rows="10" class="form-control" name="referencia">
                        
                    </textarea>
                </div>
                <div class="form-group">
                    <label for="inputAddress" class="col-form-label">Fornecedor</label>
                    <select name="idFornecedor">
                        <option value="<?=$data['id']?>" selected="selected"><?=$data['nome']?></option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </form>
        </div>
    </div>
</div>